### ISSUE TITLE
'No node by name 'Cloud Drive' found in the database.'

### ISSUE THREAD

**Issue by therealssj** [alex-phillips/clouddrive-php#16]
I keep getting this error with the new sdk. Help?

**Comment by alex-phillips** [comment]
@Mwesome You'll probably need to do a `clearcache` and resync your account. There was a change some time ago in the code that changed the `ROOT` node in the database (since it doesn't have a name) to `Cloud Drive`. Or, if you want to you can manually go into the database, find the root node and simply change it's name to "Cloud Drive".

**Comment by therealssj** [comment]
Okay i just checked the database. For some strange reason its empty. 
Syncing it now. 
Thnx!
